### ISSUE TITLE
error on large mbox file

### ISSUE THREAD

**Issue by perkfly** [emersion/go-mbox#10]
gives error `bufio.Scanner: token too long`

**Comment by blabber** [comment]
I'd guess that the buffer of your `mbox.Scanner` instance is too small. Try to increase your buffer size.

To double the buffer size you'd do something like this (untested code, written out of my head):

    s := mbox.NewScanner(...)
    
    bufsize := 2*bufio.MaxScanTokenSize
    buf := make([]byte, bufsize)
    s.Buffer(buf, bufsize)

**Comment by perkfly** [comment]
thx, I actually increases the buffer size to 10 MiB

**Comment by blabber** [comment]
Sorry for answering late. Did you fix the issue by increasing the buffer size?

**Comment by perkfly** [comment]
Yeah, it works, thx

**Comment by blabber** [comment]
Cool, so I'll close this issue.
