### ISSUE TITLE
Delete

### ISSUE THREAD

**Issue by robotamer** [emersion/go-mbox#11]
How do you delete messages?

**Comment by blabber** [comment]
There is no way to simply delete messages. In the current implementation you'd have to iterate over a mbox and write the relevant messages to another mbox and finally replace the original mbox with the new one.

**Comment by robotamer** [comment]
It would be nice if you could mention that in the Readme file.
I am not the first one, people waist time trying to implement your code.
For example:
https://github.com/emersion/go-imap-mbox

**Comment by blabber** [comment]
In my opinion this package does what it advertises: "Package mbox parses the mbox file format into messages and formats messages into mbox files."

It is not a full fledged mbox management package, but maybe I should make that stand  out a bit more.

In the beginning mbox supported only reading a mbox file into messages and emersion, whose repository you point to, added the writing functionality.

**Comment by robotamer** [comment]
If you look in emersions code, he got stuck at the delete functionality as well.
Maybe it is just me, I was expecting something I could use to manage a mbox.
My point is, a small clear note would save us time, having to look though the code while doing research.

**Comment by robotamer** [comment]
By the way. I do appreciate you sharing your code.

**Comment by blabber** [comment]
I just expanded the README.md. Thanks for pointing this lack of documentation out.
