### ISSUE TITLE
I'm interested in becoming maintainer

### ISSUE THREAD

**Issue by emersion** [emersion/go-mbox#18]
>This project is in maintenance mode. I am not actively working on this package any more, but I am responding to issues and merge the occasional pull request. If you miss any functionality, feel free to send pull requests.
>
>If you are interested in taking over this package, ping me.

I'm interested in becoming maintainer of this library. I already maintain a bunch of e-mail related libraries. Thoughts?

**Comment by blabber** [comment]
I would be very happy to put this package in caring hands. If it's okay with you, I'll simply transfer ownership of this repository to your account.
Thanks for the offer.

**Comment by emersion** [comment]
Yup, works for me!

**Comment by blabber** [comment]
I initiated the transfer. Again, thanks for volunteering!
