### ISSUE TITLE
I think scanner.go is broken, at least for some usages.

### ISSUE THREAD

**Issue by morrowc** [emersion/go-mbox#4]
I've a short diff/patch which I'll turn into a pull request shortly.
(I need the issue number for the branch name)

**Comment by morrowc** [comment]
argh, actually that's hard.. here's the diff/patch:
------------------- start patch -----------------
diff --git a/scanner.go b/scanner.go
index 77f01ee..6b8bd73 100644
--- a/scanner.go
+++ b/scanner.go
@@ -79,6 +79,8 @@ type Scanner struct {
 // provided by io.Reader r.
 func NewScanner(r io.Reader) *Scanner {
 	s := bufio.NewScanner(r)
+	buf := make([]byte, 0, 64*1024)
+	s.Buffer(buf, 1024*1024*100)
 	s.Split(scanMessage)
 
 	return &Scanner{s, nil, nil}
@@ -125,7 +127,6 @@ func (m *Scanner) Message() *mail.Message {
 	return m.m
 }
 
-
 // Buffer sets the initial buffer to use when scanning and the maximum size of
 // buffer that may be allocated during scanning.
 //

-------------------------- end patch -----------------

note that the change at line 125 seems to be some gofmt fix only.

**Comment by morrowc** [comment]
and I'll do the editing for this in the github editor... so maybe I can make a local-to-github pull request in  a sane fashion.

**Comment by morrowc** [comment]
https://github.com/blabber/mbox/pull/5

**Comment by blabber** [comment]
Hi, I updated the README.md. I decided to keep the vanished repository in it (strokethrough though) just to document that I checked two alternatives befor rolling my own solution. I also changed the TravisCI configuration, so that coveralls.io is no longer used for pull requests.

Thanks for pointing out these issues.
